"""
Module C: Bayesian Recommender (FIXED VERSION)

SCIENTIFIC FIX: Method-specific assumption constraints.

This version implements:
1. Explicit method-assumption mapping
2. Risk-based abstention (not heuristic thresholds)
3. Method-specific admissibility
4. Uses learned calibration insights
5. Scientifically coherent decision logic

v0.1: Two strategies (RobustDefault=PCMCI+, ComputeLight=VAR-based Granger) + Abstain.
v0.2: Add Specialized strategies, per-method catastrophic risk.
"""

from dataclasses import dataclass, asdict
from typing import Dict, Any, Optional, List, Tuple
import warnings
from datetime import datetime

import numpy as np

from .b_quantifier import RiskProfile


@dataclass
class Policy:
    """Recommendation policy (Module C output)."""

    # Schema metadata
    schema_version: str
    timestamp: str

    # Decision
    decision: str  # "recommend" or "abstain"
    recommended_method: Optional[str]
    confidence: Optional[float]

    # Policy reason codes (stable enums for downstream branching)
    policy_reason_codes: List[str]

    # Method configuration (if recommend)
    method_config: Optional[Dict[str, Any]]

    # Provenance
    provenance: Dict[str, Any]

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return asdict(self)


@dataclass
class Scorecard:
    """Human-readable recommendation scorecard."""

    # Summary
    decision: str
    recommended_method: Optional[str]
    confidence: Optional[float]

    # Risk ledger (from RiskProfile)
    risk_summary: Dict[str, Any]

    # Rationale
    rationale: str

    # Utility breakdown
    utility_breakdown: Optional[Dict[str, float]]

    # Value-of-Information messages
    voi_messages: List[str]

    # Abstention explanation (if abstain)
    abstention_explanation: Optional[Dict[str, Any]]

    def to_markdown(self) -> str:
        """Generate markdown scorecard."""
        md = f"# Causal Discovery Audit Scorecard\n\n"
        md += f"## Decision: **{self.decision.upper()}**\n\n"

        if self.decision == "recommend":
            md += f"**Recommended Method**: {self.recommended_method}\n\n"
            md += f"**Confidence**: {self.confidence:.2%}\n\n"

        md += f"## Rationale\n\n{self.rationale}\n\n"

        if self.abstention_explanation:
            md += "## Why Not Run Anything?\n\n"
            md += self.abstention_explanation.get("summary", "") + "\n\n"
            md += "**Top Contributors**:\n\n"
            for contrib in self.abstention_explanation.get("top_contributors", []):
                md += f"- {contrib['risk']}: {contrib['value']:.3f} (trigger: {contrib['trigger']})\n"
            md += f"\n**Rule Fired**: {self.abstention_explanation.get('rule_fired', 'N/A')}\n\n"

        md += "## Risk Summary\n\n"
        for risk, values in self.risk_summary.items():
            mean = values.get("mean", 0)
            lower = values.get("lower_95", 0)
            upper = values.get("upper_95", 0)
            md += f"- **{risk}**: {mean:.3f} [{lower:.3f}, {upper:.3f}]\n"

        if self.utility_breakdown:
            md += "\n## Utility Breakdown\n\n"
            for strategy, util in self.utility_breakdown.items():
                md += f"- {strategy}: {util:.3f}\n"

        if self.voi_messages:
            md += "\n## Value of Information\n\n"
            for msg in self.voi_messages:
                md += f"- {msg}\n"

        md += "\n---\n\n"
        md += "*Generated by causal-audit v0.2 (Fixed Recommender)*\n"

        return md


class MethodRecommender:
    """
    Recommend causal discovery method via method-specific constraints.

    SCIENTIFIC FIX: Uses explicit assumption mapping instead of heuristic utilities.
    """

    # Method-Assumption Mapping (SCIENTIFICALLY GROUNDED)
    METHOD_CONSTRAINTS = {
        "PCMCI+": {
            "hard_constraints": [
                # PCMCI+ has no hard constraints on nonstationarity — it can be applied
                # after detrending/deseasonalization. The recommendation will include
                # a preprocessing note when NonstationarityRisk is high.
            ],
            "soft_constraints": [
                (
                    "ConfoundingRisk",
                    0.80,
                    "Partially robust to latent confounders via conditioning (less critical than Granger)",
                ),
                (
                    "PersistenceRisk",
                    0.85,
                    "High persistence requires large tau_max (computational cost)",
                ),
                (
                    "IrregularityRisk",
                    0.60,
                    "Missing data handled by CI tests but reduces power",
                ),
            ],
            "robustness": {
                "irregularity": "high",  # CI tests handle missing data well
                "nonlinearity": "moderate",  # Conditional independence tests
                "nongaussianity": "high",  # Rank-based tests available
            },
            "base_cost": 1.0,
            "description": "Robust causal discovery with conditional independence tests",
        },
        "Granger": {
            "hard_constraints": [
                (
                    "NonstationarityRisk",
                    0.95,
                    "VAR requires stationarity or differencing (parameter estimation fails on unit roots)",
                ),
                (
                    "ConfoundingRisk",
                    0.60,
                    "Cannot handle latent confounders (biased estimates - more sensitive than PCMCI+)",
                ),
                (
                    "IrregularityRisk",
                    0.50,
                    "Requires regular sampling (VAR assumes fixed intervals)",
                ),
            ],
            "soft_constraints": [
                (
                    "PersistenceRisk",
                    0.75,
                    "VAR lag selection bounded by AIC (may miss long lags)",
                ),
            ],
            "robustness": {
                "irregularity": "low",  # Requires regular sampling
                "nonlinearity": "low",  # Linear VAR assumption
                "nongaussianity": "moderate",  # F-tests assume normality
            },
            "base_cost": 0.1,
            "description": "Fast VAR-based Granger causality (requires strong assumptions)",
        },
    }

    # Preregistered parameters
    LAMBDA_CPU = 0.01  # Cost weight

    # Abstention thresholds (revised to be risk-based)
    T_EFF_RATIO_THRESHOLD = 0.30  # Minimum effective sample ratio
    CONFIDENCE_THRESHOLD = 0.60  # Minimum confidence for recommendation

    def __init__(
        self,
        method_catalog_file: Optional[str] = None,
        priors_file: Optional[str] = None,
        calibration_file: Optional[str] = None,
    ):
        """
        Initialize recommender.

        Args:
            method_catalog_file: Path to method catalog (optional, uses built-in)
            priors_file: Path to priors (optional)
            calibration_file: Path to calibration (optional)
        """
        self.method_catalog_file = method_catalog_file
        self.priors_file = priors_file
        self.calibration_file = calibration_file

    def recommend(
        self,
        risk_profile: RiskProfile,
        compute_budget: Optional[float] = None,
        t_eff_ratio: Optional[float] = None,
        force_proceed: bool = False,
    ) -> Tuple[Policy, Scorecard]:
        """
        Generate recommendation based on risk profile.

        Args:
            risk_profile: RiskProfile from Module B
            compute_budget: Optional compute budget (seconds)
            t_eff_ratio: Optional effective sample size ratio
            force_proceed: If True, override abstention and recommend best available method
                          with explicit warnings (use with caution!)

        Returns:
            (Policy, Scorecard) tuple
        """
        # Extract risk values — now includes NonlinearityRisk and SeasonalityRisk
        risks = {
            name: risk_profile.risks[name]
            for name in risk_profile.risk_names
            if name in risk_profile.risks
        }
        # Ensure backward compatibility: fill missing risks with zero
        for name in [
            "NonstationarityRisk",
            "IrregularityRisk",
            "PersistenceRisk",
            "ConfoundingRisk",  # display: "Causal insufficiency"; proxy for latent confounders
            "NonlinearityRisk",
            "SeasonalityRisk",
        ]:
            if name not in risks:
                risks[name] = {"mean": 0.0, "lower_95": 0.0, "upper_95": 0.0}

        # Collect abstention triggers (for force_proceed mode)
        abstention_warnings = []

        # Check T_eff ratio (if provided)
        # Note: T_eff/T can be very low for seasonal/autocorrelated data (e.g., 0.01 for
        # strong seasonal patterns). This is NOT a reason to abstain — PCMCI+ is designed
        # for autocorrelated time series. Only warn, never abstain on T_eff/T alone.
        if t_eff_ratio is not None and t_eff_ratio < 0.05:
            abstention_warnings.append(
                {
                    "type": "LOW_T_EFF_RATIO",
                    "message": f"Low effective sample size: T_eff/T = {t_eff_ratio:.3f} "
                    f"(high autocorrelation detected). Use large tau_max.",
                    "severity": "WARNING",
                }
            )

        # Step 0b: Check for high uncertainty (interval width > 0.5)
        # Exclude ConfoundingRisk (VIF CIs are inherently wide) and IrregularityRisk
        # (gap CV estimates are noisy). Only abstain on structural risks.
        for risk_name, risk_vals in risks.items():
            if risk_name in ("ConfoundingRisk", "IrregularityRisk", "NonlinearityRisk"):
                continue
            interval_width = risk_vals["upper_95"] - risk_vals["lower_95"]
            if interval_width > 0.5:
                if not force_proceed:
                    return self._create_abstention_policy(
                        risk_profile=risk_profile,
                        reason="High uncertainty in risk estimate",
                        detail=f"{risk_name} interval width = {interval_width:.2f} > 0.5",
                        code="HIGH_UNCERTAINTY",
                    )
                else:
                    abstention_warnings.append(
                        {
                            "type": "HIGH_UNCERTAINTY",
                            "message": f"High uncertainty: {risk_name} interval width = {interval_width:.2f} > 0.5",
                            "severity": "WARNING",
                        }
                    )
                    break  # Only need to flag once

        # Step 1: Check for catastrophic violations (abstain for all methods)
        catastrophic_check = self._check_catastrophic_violations(risks)
        if catastrophic_check is not None:
            if not force_proceed:
                return self._create_abstention_policy(
                    risk_profile=risk_profile,
                    reason=catastrophic_check["reason"],
                    detail=catastrophic_check["detail"],
                    code=catastrophic_check["code"],
                )
            else:
                abstention_warnings.append(
                    {
                        "type": catastrophic_check["code"],
                        "message": f"{catastrophic_check['reason']}: {catastrophic_check['detail']}",
                        "severity": "CRITICAL",
                    }
                )

        # Step 2: Check method admissibility
        pcmci_admissible, pcmci_reason = self._check_method_admissibility(
            "PCMCI+", risks
        )
        granger_admissible, granger_reason = self._check_method_admissibility(
            "Granger", risks
        )

        # Step 3: Make decision
        if not pcmci_admissible and not granger_admissible:
            if not force_proceed:
                return self._create_abstention_policy(
                    risk_profile=risk_profile,
                    reason="No admissible method",
                    detail="Both PCMCI+ and Granger have violated hard constraints",
                    code="NO_ADMISSIBLE_METHOD",
                    violations=[pcmci_reason, granger_reason],
                )
            else:
                # Force proceed: choose least-worst option (PCMCI+ as it's more robust)
                abstention_warnings.append(
                    {
                        "type": "NO_ADMISSIBLE_METHOD",
                        "message": "Both methods violate hard constraints - proceeding with PCMCI+ (most robust)",
                        "severity": "CRITICAL",
                        "violations": [pcmci_reason, granger_reason],
                    }
                )
                return self._create_forced_recommendation_policy(
                    risk_profile=risk_profile,
                    method="PCMCI+",
                    confidence=0.40,  # Very low confidence
                    reason="FORCED: No admissible method - using PCMCI+ as least-worst option",
                    warnings=abstention_warnings,
                )

        if pcmci_admissible and not granger_admissible:
            warnings = abstention_warnings + (
                [
                    {
                        "type": "METHOD_VIOLATION",
                        "message": granger_reason,
                        "severity": "INFO",
                    }
                ]
                if granger_reason
                else []
            )
            return self._create_recommendation_policy(
                risk_profile=risk_profile,
                method="PCMCI+",
                confidence=0.85
                if not abstention_warnings
                else 0.65,  # Lower confidence if force_proceed
                reason="PCMCI+ admissible (robust to moderate confounding/persistence)"
                + (" - FORCED" if abstention_warnings else ""),
                warnings=warnings,
            )

        if granger_admissible and not pcmci_admissible:
            warnings = abstention_warnings + (
                [
                    {
                        "type": "METHOD_VIOLATION",
                        "message": pcmci_reason,
                        "severity": "INFO",
                    }
                ]
                if pcmci_reason
                else []
            )
            return self._create_recommendation_policy(
                risk_profile=risk_profile,
                method="Granger",
                confidence=0.75
                if not abstention_warnings
                else 0.55,  # Lower confidence if force_proceed
                reason="Granger admissible (low confounding, stationary data)"
                + (" - FORCED" if abstention_warnings else ""),
                warnings=warnings,
            )

        # Both admissible → choose based on data properties (nonlinearity, confounding, seasonality, persistence)
        nonlin_mean = risks["NonlinearityRisk"]["mean"]
        confound_mean = risks["ConfoundingRisk"]["mean"]
        persist_mean = risks["PersistenceRisk"]["mean"]
        nonstat_mean = risks["NonstationarityRisk"]["mean"]
        seasonal_mean = risks["SeasonalityRisk"]["mean"]

        # Compute data-driven confidence: penalize for each elevated risk
        base_confidence = 0.90
        confidence_penalty = (
            0.15 * min(nonlin_mean, 1.0)
            + 0.10 * min(confound_mean, 1.0)
            + 0.10 * min(persist_mean, 1.0)
            + 0.05 * min(nonstat_mean, 1.0)
            + 0.05 * min(seasonal_mean, 1.0)
        )
        data_driven_confidence = max(0.40, base_confidence - confidence_penalty)

        # Decision tree: nonlinearity and confounding drive method selection
        if nonlin_mean > 0.35:
            # Nonlinear data: PCMCI+(CMIknn) or Transfer Entropy preferred
            method = "PCMCI+"
            reason = (
                f"NonlinearityRisk={nonlin_mean:.2f} > 0.35: polynomial/nonlinear "
                f"dependencies detected. ParCorr/Granger will miss these. "
                f"PCMCI+(CMIknn) or Transfer Entropy recommended."
            )
            method_config = {
                "pcmci": {
                    "enabled": True,
                    "test_method": "cmiknn",
                    "allow_contemporaneous": True,
                },
                "transfer_entropy": {"enabled": True},
                "granger": {"enabled": True, "note": "linear baseline only"},
            }
            return self._create_recommendation_policy(
                risk_profile=risk_profile,
                method=method,
                confidence=round(data_driven_confidence, 2),
                reason=reason,
                method_config=method_config,
                warnings=abstention_warnings,
            )

        if confound_mean > 0.45:
            # Latent confounders suspected: LPCMCI preferred
            method = "LPCMCI"
            reason = (
                f"ConfoundingRisk={confound_mean:.2f} > 0.35: latent confounders "
                f"suspected. Standard PCMCI+ may produce spurious edges. "
                f"LPCMCI (FCI-based) recommended."
            )
            method_config = {
                "lpcmci": {"enabled": True},
                "pcmci": {
                    "enabled": True,
                    "test_method": "parcorr",
                    "note": "fallback if LPCMCI too slow",
                },
                "granger": {"enabled": True, "note": "linear baseline only"},
            }
            return self._create_recommendation_policy(
                risk_profile=risk_profile,
                method=method,
                confidence=round(data_driven_confidence, 2),
                reason=reason,
                method_config=method_config,
                warnings=abstention_warnings,
            )

        if seasonal_mean > 0.30:
            # Trend+seasonality: dedicated SeasonalityRisk dimension
            # Detrend first, then PCMCI+(ParCorr) on residuals
            method = "PCMCI+"
            reason = (
                f"SeasonalityRisk={seasonal_mean:.2f} > 0.30: deterministic trend or "
                f"seasonal components detected. Deseasonalize/detrend before discovery. "
                f"PCMCI+(ParCorr) on residuals recommended."
            )
            method_config = {
                "pcmci": {
                    "enabled": True,
                    "test_method": "parcorr",
                    "allow_contemporaneous": True,
                },
                "granger": {"enabled": True, "note": "linear baseline"},
                "preprocessing": {"deseasonalize": True},
            }
            return self._create_recommendation_policy(
                risk_profile=risk_profile,
                method=method,
                confidence=round(data_driven_confidence, 2),
                reason=reason,
                method_config=method_config,
                warnings=abstention_warnings,
            )

        if nonstat_mean > 0.40 and seasonal_mean <= 0.30:
            # Structural breaks or drift (not seasonal): detrend + PCMCI+
            method = "PCMCI+"
            reason = (
                f"NonstationarityRisk={nonstat_mean:.2f} > 0.40 (structural breaks or drift, "
                f"SeasonalityRisk={seasonal_mean:.2f} low). Detrend before discovery."
            )
            method_config = {
                "pcmci": {
                    "enabled": True,
                    "test_method": "parcorr",
                    "allow_contemporaneous": True,
                },
                "granger": {"enabled": True, "note": "linear baseline"},
                "preprocessing": {"deseasonalize": True},
            }
            return self._create_recommendation_policy(
                risk_profile=risk_profile,
                method=method,
                confidence=round(data_driven_confidence, 2),
                reason=reason,
                method_config=method_config,
                warnings=abstention_warnings,
            )

        if persist_mean > 0.70:
            # High persistence → prefer PCMCI+ (handles long lags better)
            return self._create_recommendation_policy(
                risk_profile=risk_profile,
                method="PCMCI+",
                confidence=round(data_driven_confidence, 2),
                reason=f"PersistenceRisk={persist_mean:.2f} > 0.70: high autocorrelation. "
                f"PCMCI+ with large tau_max preferred over Granger.",
                warnings=abstention_warnings,
            )

        # Low risk, linear, no confounders, no seasonality → PCMCI+(ParCorr) is optimal
        return self._create_recommendation_policy(
            risk_profile=risk_profile,
            method="PCMCI+",
            confidence=round(data_driven_confidence, 2),
            reason=(
                f"Low risk profile (nonlin={nonlin_mean:.2f}, confound={confound_mean:.2f}, "
                f"seasonal={seasonal_mean:.2f}, nonstat={nonstat_mean:.2f}): "
                f"linear Gaussian data. PCMCI+(ParCorr) recommended for best FDR control."
            ),
            method_config={
                "pcmci": {
                    "enabled": True,
                    "test_method": "parcorr",
                    "allow_contemporaneous": True,
                },
                "granger": {"enabled": True, "note": "fast linear baseline"},
            },
            warnings=abstention_warnings,
        )

    def _check_catastrophic_violations(self, risks: Dict) -> Optional[Dict]:
        """Check for catastrophic violations that invalidate all methods."""

        nonstat = risks["NonstationarityRisk"]["mean"]
        confound = risks["ConfoundingRisk"]["mean"]

        # Very high nonstationarity (>0.95) — check if it's due to seasonality
        # (manageable with detrending) or unit root (catastrophic)
        if nonstat > 0.95:
            # Check if seasonality is the cause (from risk ledger)
            # If NonlinearityRisk is low but NonstationarityRisk is extreme,
            # it's likely trend/seasonality rather than a unit root.
            # Route to "detrend first" recommendation rather than abstaining.
            nonlin = risks.get("NonlinearityRisk", {}).get("mean", 0.0)
            if nonlin < 0.30:
                # Likely trend/seasonality: recommend detrending + PCMCI+
                # (handled in the main decision tree below)
                pass  # Don't abstain; fall through to decision tree
            else:
                return {
                    "reason": "Critical nonstationarity with nonlinearity",
                    "detail": f"NonstationarityRisk={nonstat:.2f} AND NonlinearityRisk={nonlin:.2f}: "
                    f"likely explosive nonlinear process",
                    "code": "CRITICAL_NONSTATIONARITY",
                }

        # Multiple high risks (nonstationarity + confounding) — only abstain if both extreme
        # AND nonlinearity is also high (ruling out seasonal multicollinearity as the cause)
        nonlin = risks.get("NonlinearityRisk", {}).get("mean", 0.0)
        if nonstat > 0.90 and confound > 0.90 and nonlin > 0.30:
            return {
                "reason": "Multiple critical violations",
                "detail": f"NonstationarityRisk={nonstat:.2f}, ConfoundingRisk={confound:.2f}, "
                f"NonlinearityRisk={nonlin:.2f}: complex data structure",
                "code": "MULTIPLE_CRITICAL_VIOLATIONS",
            }

        # Composite risk exceeding 0.90 (NonstationarityRisk only — the most critical)
        # PersistenceRisk and IrregularityRisk are handled by method selection, not abstention.
        if nonstat > 0.95:
            # Already handled above (only abstain if nonlinear too)
            pass

        return None

    def _check_method_admissibility(
        self, method: str, risks: Dict
    ) -> Tuple[bool, Optional[str]]:
        """
        Check if method's hard constraints are satisfied.

        Returns:
            (admissible, reason_if_not)
        """
        constraints = self.METHOD_CONSTRAINTS[method]

        # Check hard constraints
        for risk_name, threshold, description in constraints["hard_constraints"]:
            risk_mean = risks[risk_name]["mean"]
            risk_lower = risks[risk_name]["lower_95"]

            # Conservative: Even lower bound exceeds threshold → definitely violated
            if risk_lower > threshold:
                return (
                    False,
                    f"{method}: {description} (lower 95% = {risk_lower:.2f} > {threshold})",
                )

            # Mean exceeds threshold → likely violated
            if risk_mean > threshold:
                return (
                    False,
                    f"{method}: {description} (mean = {risk_mean:.2f} > {threshold})",
                )

        return True, None

    def _create_recommendation_policy(
        self,
        risk_profile: RiskProfile,
        method: str,
        confidence: float,
        reason: str,
        detail: Optional[str] = None,
        warnings: Optional[List] = None,  # Can be List[str] or List[Dict]
        method_config: Optional[Dict[str, Any]] = None,
    ) -> Tuple[Policy, Scorecard]:
        """Create recommendation policy."""

        timestamp = datetime.now().isoformat()

        # Build method config — use caller-provided config if given, else defaults
        if method_config is None:
            method_config = {
                "method": method,
                "tau_max": 12,  # Default, can be adjusted based on persistence
                "alpha": 0.05,
                "ci_test": "ParCorr" if method == "PCMCI+" else "F-test",
                "fdr_method": "BY",  # Benjamini-Yekutieli
            }
        else:
            # Merge with defaults
            method_config.setdefault("method", method)
            method_config.setdefault("tau_max", 12)
            method_config.setdefault("alpha", 0.05)
            method_config.setdefault("fdr_method", "fdr_bh")

        # Adjust tau_max for high persistence
        persist_mean = risk_profile.risks["PersistenceRisk"]["mean"]
        if persist_mean > 0.75:
            method_config["tau_max"] = 20  # Increase for high persistence

        # Build reason codes
        reason_codes = ["RECOMMEND"]
        if persist_mean > 0.75:
            reason_codes.append("HIGH_PERSISTENCE_DETECTED")
        if method == "Granger":
            reason_codes.append("COMPUTE_EFFICIENT_SELECTED")
        if method == "PCMCI+":
            reason_codes.append("ROBUST_METHOD_SELECTED")

        # Check for forced recommendation (CRITICAL warnings present)
        forced = False
        if warnings:
            for w in warnings:
                if isinstance(w, dict) and w.get("severity") == "CRITICAL":
                    forced = True
                    reason_codes.append("FORCED_RECOMMENDATION")
                    break

        # Create policy
        policy = Policy(
            schema_version="2.0.0",
            timestamp=timestamp,
            decision="recommend",
            recommended_method=method,
            confidence=confidence,
            policy_reason_codes=reason_codes,
            method_config=method_config,
            provenance={
                "causal_audit_version": "0.2.0",
                "recommender_version": "fixed",
                "decision_logic": "method_specific_constraints",
                "forced": forced,
            },
        )

        # Build rationale
        rationale_parts = [reason]
        if detail:
            rationale_parts.append(detail)
        if warnings:
            warning_strs = []
            for w in warnings:
                if isinstance(w, dict):
                    severity = w.get("severity", "INFO")
                    msg = w.get("message", str(w))
                    warning_strs.append(f"[{severity}] {msg}")
                else:
                    warning_strs.append(str(w))

            if warning_strs:
                rationale_parts.append(
                    "**WARNINGS:**\n" + "\n".join(f"  - {w}" for w in warning_strs)
                )

        rationale = "\n\n".join(rationale_parts)

        # Create scorecard
        scorecard = Scorecard(
            decision="recommend",
            recommended_method=method,
            confidence=confidence,
            risk_summary=risk_profile.risks,
            rationale=rationale,
            utility_breakdown=None,  # Not used in fixed version
            voi_messages=[],
            abstention_explanation=None,
        )

        return policy, scorecard

    def _create_forced_recommendation_policy(
        self,
        risk_profile: RiskProfile,
        method: str,
        confidence: float,
        reason: str,
        warnings: List[Dict[str, Any]],
    ) -> Tuple[Policy, Scorecard]:
        """Create forced recommendation policy (overriding abstention)."""
        # Just call the regular method - it now handles forced recommendations
        return self._create_recommendation_policy(
            risk_profile=risk_profile,
            method=method,
            confidence=confidence,
            reason=reason,
            warnings=warnings,
        )

    def _create_abstention_policy(
        self,
        risk_profile: RiskProfile,
        reason: str,
        detail: str,
        code: str,
        violations: Optional[List[str]] = None,
    ) -> Tuple[Policy, Scorecard]:
        """Create abstention policy."""

        timestamp = datetime.now().isoformat()

        # Create policy
        policy = Policy(
            schema_version="2.0.0",
            timestamp=timestamp,
            decision="abstain",
            recommended_method=None,
            confidence=None,
            policy_reason_codes=["ABSTAIN", code],
            method_config=None,
            provenance={
                "causal_audit_version": "0.2.0",
                "recommender_version": "fixed",
                "decision_logic": "method_specific_constraints",
            },
        )

        # Build abstention explanation
        top_contributors = []
        for risk_name, risk_values in risk_profile.risks.items():
            if risk_values["mean"] > 0.70:  # High risk
                top_contributors.append(
                    {
                        "risk": risk_name,
                        "value": risk_values["mean"],
                        "trigger": f"mean > 0.70",
                    }
                )

        # Sort by value
        top_contributors = sorted(
            top_contributors, key=lambda x: x["value"], reverse=True
        )[:3]

        abstention_explanation = {
            "summary": reason,
            "detail": detail,
            "top_contributors": top_contributors,
            "rule_fired": code,
            "violations": violations or [],
        }

        # Build rationale
        rationale_parts = [reason, detail]
        if violations:
            rationale_parts.append(
                "\n**Method constraints violated:**\n"
                + "\n".join(f"- {v}" for v in violations)
            )

        rationale = "\n\n".join(rationale_parts)

        # Create scorecard
        scorecard = Scorecard(
            decision="abstain",
            recommended_method=None,
            confidence=None,
            risk_summary=risk_profile.risks,
            rationale=rationale,
            utility_breakdown=None,
            voi_messages=[],
            abstention_explanation=abstention_explanation,
        )

        return policy, scorecard
